# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 905)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/imcIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBar = QtWidgets.QFrame(self.centralwidget)
        self.topBar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.topBar.setStyleSheet("")
        self.topBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBar.setObjectName("topBar")
        self.verticalLayout.addWidget(self.topBar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginArea = QtWidgets.QFrame(self.content)
        self.loginArea.setMaximumSize(QtCore.QSize(450, 550))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.loginArea.setFont(font)
        self.loginArea.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.loginArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.loginArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginArea.setObjectName("loginArea")
        self.frameLogo = QtWidgets.QFrame(self.loginArea)
        self.frameLogo.setGeometry(QtCore.QRect(150, 0, 150, 161))
        self.frameLogo.setStyleSheet("background-image: url(:/logo/img/iconeIMC_150.png);\n"
"background-repeat:no repeat;\n"
"background-position:center;")
        self.frameLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogo.setObjectName("frameLogo")
        self.frameLogin = QtWidgets.QFrame(self.loginArea)
        self.frameLogin.setGeometry(QtCore.QRect(150, 190, 150, 45))
        self.frameLogin.setStyleSheet("background-image: url(:/login/img/LOGIN1.png);\n"
"background-position:center;\n"
"backgroudn-repeat:no-repeat;")
        self.frameLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogin.setObjectName("frameLogin")
        self.lineEdit_userName = QtWidgets.QLineEdit(self.loginArea)
        self.lineEdit_userName.setGeometry(QtCore.QRect(85, 270, 280, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.lineEdit_userName.setFont(font)
        self.lineEdit_userName.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(45,45,45);\n"
"border-radius:5px;\n"
"padding:10px;\n"
"background-color:rgb(30,30,30);\n"
"color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus{\n"
"border:2px solid rgb(255, 255, 114);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lineEdit_userName.setMaxLength(32)
        self.lineEdit_userName.setObjectName("lineEdit_userName")
        self.lineEdit_password = QtWidgets.QLineEdit(self.loginArea)
        self.lineEdit_password.setGeometry(QtCore.QRect(85, 315, 280, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(45,45,45);\n"
"border-radius:5px;\n"
"padding:10px;\n"
"background-color:rgb(30,30,30);\n"
"color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus{\n"
"border:2px solid rgb(255, 255, 114);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lineEdit_password.setMaxLength(16)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_conectar = QtWidgets.QPushButton(self.loginArea)
        self.pushButton_conectar.setGeometry(QtCore.QRect(85, 380, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_conectar.setFont(font)
        self.pushButton_conectar.setStyleSheet("QPushButton{\n"
"background-color: rgb(50, 50, 50);\n"
"border:2px solid rgb(60,60,60);\n"
"border-radius:5px;\n"
"color: rgb(100, 100, 100);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 255, 127);\n"
"border:2px solid rgb(70,70,70);\n"
"color: rgb(100, 100, 100);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(255, 255, 127);\n"
"border:2px solid rgb(70,70,70);\n"
"color: rgb(85, 85, 85);\n"
"\n"
"}\n"
"")
        self.pushButton_conectar.setObjectName("pushButton_conectar")
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.loginArea)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(85, 440, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cadastrar.setFont(font)
        self.pushButton_cadastrar.setStyleSheet("QPushButton{\n"
"background-color: rgb(50, 50, 50);\n"
"border:2px solid rgb(60,60,60);\n"
"border-radius:5px;\n"
"color: rgb(100, 100, 100);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 255, 127);\n"
"border:2px solid rgb(70,70,70);\n"
"color: rgb(100, 100, 100);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(255, 255, 127);\n"
"border:2px solid rgb(70,70,70);\n"
"color: rgb(85, 85, 85);\n"
"\n"
"}\n"
"")
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.horizontalLayout.addWidget(self.loginArea)
        self.verticalLayout.addWidget(self.content)
        self.botton = QtWidgets.QFrame(self.centralwidget)
        self.botton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.botton.setStyleSheet("background-color: rgb(10, 10, 10);")
        self.botton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.botton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.botton.setObjectName("botton")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.botton)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.botton)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(131, 131, 131);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.botton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login - Calculadora IMC"))
        self.lineEdit_userName.setPlaceholderText(_translate("MainWindow", "USERNAME"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.pushButton_conectar.setText(_translate("MainWindow", "CONECTAR"))
        self.pushButton_cadastrar.setText(_translate("MainWindow", "CADASTRE-SE"))
        self.label.setText(_translate("MainWindow", "Criado por: Gabriel Baltazar"))
import img_logo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
